require("prototypes.sprites")
require("prototypes.resources")
require("prototypes.items")
require("prototypes.recipes")
require("prototypes.technology")
require("prototypes.entities")
require("prototypes.equipment")
require("prototypes.tiles")
